"""Curated/mock dataset of ~30 indoor activities for youth hubs in Lahore,
Karachi, and Islamabad. Coordinates are approximate for demo purposes.

Each event carries a `host_phone` in international format (no +, no spaces)
so the Booking Engine can build a wa.me deep link.
"""

EVENTS = [
    {
        "event_id": "evt_001",
        "name": "Beginner Pottery Wheel Session",
        "activity_type": "pottery",
        "location": "Johar Town",
        "city": "Lahore",
        "lat": 31.4697, "lng": 74.2728,
        "time": "Today, 4:00 PM",
        "price": "PKR 1500",
        "host_name": "Clay Corner Studio",
        "host_phone": "923001234501",
        "description": "Hands-on wheel throwing for first-timers, clay and apron included.",
    },
    {
        "event_id": "evt_002",
        "name": "Tote Bag Painting Circle",
        "activity_type": "painting",
        "location": "Gulberg",
        "city": "Lahore",
        "lat": 31.5099, "lng": 74.3436,
        "time": "Today, 5:00 PM",
        "price": "PKR 1200",
        "host_name": "Brush & Canvas",
        "host_phone": "923001234502",
        "description": "Paint your own tote with acrylics, all materials provided, small group.",
    },
    {
        "event_id": "evt_003",
        "name": "Board Game Night",
        "activity_type": "board games",
        "location": "MM Alam Road",
        "city": "Lahore",
        "lat": 31.5074, "lng": 74.3453,
        "time": "Today, 7:00 PM",
        "price": "PKR 800",
        "host_name": "Colabs Gaming Lounge",
        "host_phone": "923001234503",
        "description": "Catan, Codenames, and Werewolf rounds with snacks and chai.",
    },
    {
        "event_id": "evt_004",
        "name": "Open Mic Poetry & Music",
        "activity_type": "open mic",
        "location": "Liberty Market",
        "city": "Lahore",
        "lat": 31.5089, "lng": 74.3428,
        "time": "Tonight, 8:00 PM",
        "price": "PKR 500",
        "host_name": "T2F Lahore",
        "host_phone": "923001234504",
        "description": "Sign up on arrival, five minutes per performer, poetry or acoustic sets welcome.",
    },
    {
        "event_id": "evt_005",
        "name": "Urdu Calligraphy Workshop",
        "activity_type": "calligraphy",
        "location": "DHA Phase 5",
        "city": "Lahore",
        "lat": 31.4740, "lng": 74.4130,
        "time": "Tomorrow, 3:00 PM",
        "price": "PKR 1800",
        "host_name": "Qalam Studio",
        "host_phone": "923001234505",
        "description": "Learn Nastaliq basics with reed pens and ink, take your piece home.",
    },
    {
        "event_id": "evt_006",
        "name": "Candle Making Workshop",
        "activity_type": "candle making",
        "location": "Bahria Town",
        "city": "Lahore",
        "lat": 31.3688, "lng": 74.1830,
        "time": "Today, 6:00 PM",
        "price": "PKR 2000",
        "host_name": "Wick & Wax",
        "host_phone": "923001234506",
        "description": "Pour and scent your own soy candles, three jars to take home.",
    },
    {
        "event_id": "evt_007",
        "name": "Life Drawing Session",
        "activity_type": "drawing",
        "location": "Model Town",
        "city": "Lahore",
        "lat": 31.4830, "lng": 74.3260,
        "time": "Today, 5:30 PM",
        "price": "PKR 1000",
        "host_name": "Sketch Society",
        "host_phone": "923001234507",
        "description": "Timed sketching practice, charcoal and pencils, all levels welcome.",
    },
    {
        "event_id": "evt_008",
        "name": "Hip-Hop Dance Workshop",
        "activity_type": "dance",
        "location": "Cavalry Ground",
        "city": "Lahore",
        "lat": 31.5290, "lng": 74.3670,
        "time": "Tonight, 7:30 PM",
        "price": "PKR 1000",
        "host_name": "Beatbox Dance Studio",
        "host_phone": "923001234508",
        "description": "One-hour choreography class, no experience needed, comfortable shoes only.",
    },
    {
        "event_id": "evt_009",
        "name": "Stand-Up Comedy Open Night",
        "activity_type": "comedy",
        "location": "Gulberg",
        "city": "Lahore",
        "lat": 31.5133, "lng": 74.3400,
        "time": "Tonight, 9:00 PM",
        "price": "PKR 700",
        "host_name": "Punchline Lahore",
        "host_phone": "923001234509",
        "description": "Local comics test new material, walk-in seating.",
    },
    {
        "event_id": "evt_010",
        "name": "Cozy Book Club Meetup",
        "activity_type": "book club",
        "location": "Faisal Town",
        "city": "Lahore",
        "lat": 31.4820, "lng": 74.3060,
        "time": "Today, 4:30 PM",
        "price": "Free",
        "host_name": "Pageturners Lahore",
        "host_phone": "923001234510",
        "description": "This month's pick discussion over chai, newcomers welcome.",
    },
    {
        "event_id": "evt_011",
        "name": "One-Pot Cooking Class",
        "activity_type": "cooking",
        "location": "Clifton Block 2",
        "city": "Karachi",
        "lat": 24.8138, "lng": 67.0299,
        "time": "Today, 5:00 PM",
        "price": "PKR 2200",
        "host_name": "Masala Kitchen Studio",
        "host_phone": "923001234511",
        "description": "Cook and eat a full one-pot meal together, ingredients provided.",
    },
    {
        "event_id": "evt_012",
        "name": "Karachi Poetry Slam",
        "activity_type": "open mic",
        "location": "Saddar",
        "city": "Karachi",
        "lat": 24.8570, "lng": 67.0181,
        "time": "Tonight, 8:30 PM",
        "price": "PKR 500",
        "host_name": "T2F Karachi",
        "host_phone": "923001234512",
        "description": "Bilingual poetry slam with a small house band, sign-ups at the door.",
    },
    {
        "event_id": "evt_013",
        "name": "Escape Room: The Vault",
        "activity_type": "escape room",
        "location": "DHA Phase 6",
        "city": "Karachi",
        "lat": 24.8020, "lng": 67.0640,
        "time": "Today, 6:00 PM",
        "price": "PKR 1500 per person",
        "host_name": "Locked In Karachi",
        "host_phone": "923001234513",
        "description": "60-minute heist-themed room, groups of 4 to 6, book the full slot.",
    },
    {
        "event_id": "evt_014",
        "name": "Ceramics & Glazing Workshop",
        "activity_type": "pottery",
        "location": "PECHS",
        "city": "Karachi",
        "lat": 24.8690, "lng": 67.0620,
        "time": "Tomorrow, 4:00 PM",
        "price": "PKR 1700",
        "host_name": "Mud & Fire Ceramics",
        "host_phone": "923001234514",
        "description": "Glaze a bisque-fired piece, pickup after kiln firing next week.",
    },
    {
        "event_id": "evt_015",
        "name": "Terrarium Building Session",
        "activity_type": "terrarium building",
        "location": "Bahadurabad",
        "city": "Karachi",
        "lat": 24.8770, "lng": 67.0570,
        "time": "Today, 5:30 PM",
        "price": "PKR 1600",
        "host_name": "Green Jar Studio",
        "host_phone": "923001234515",
        "description": "Build a mini glass terrarium to take home, plants and soil included.",
    },
    {
        "event_id": "evt_016",
        "name": "Indie Film Screening + Discussion",
        "activity_type": "film screening",
        "location": "Boat Basin",
        "city": "Karachi",
        "lat": 24.8090, "lng": 67.0330,
        "time": "Tonight, 8:00 PM",
        "price": "PKR 600",
        "host_name": "Frame by Frame",
        "host_phone": "923001234516",
        "description": "Short film selection followed by an open discussion over tea.",
    },
    {
        "event_id": "evt_017",
        "name": "Garage Jam Session",
        "activity_type": "jam session",
        "location": "North Nazimabad",
        "city": "Karachi",
        "lat": 24.9330, "lng": 67.0480,
        "time": "Today, 7:00 PM",
        "price": "PKR 500",
        "host_name": "Loudspeaker Collective",
        "host_phone": "923001234517",
        "description": "Bring an instrument or just come sing along, all genres welcome.",
    },
    {
        "event_id": "evt_018",
        "name": "General Knowledge Trivia Night",
        "activity_type": "trivia",
        "location": "Zamzama",
        "city": "Karachi",
        "lat": 24.8210, "lng": 67.0300,
        "time": "Today, 7:30 PM",
        "price": "PKR 400 per team",
        "host_name": "Quiz Quarters",
        "host_phone": "923001234518",
        "description": "Teams of 4, six rounds, winner takes a food voucher.",
    },
    {
        "event_id": "evt_019",
        "name": "Henna Art Workshop",
        "activity_type": "henna",
        "location": "Gulshan-e-Iqbal",
        "city": "Karachi",
        "lat": 24.9200, "lng": 67.0940,
        "time": "Tomorrow, 3:30 PM",
        "price": "PKR 900",
        "host_name": "Mehndi Studio K",
        "host_phone": "923001234519",
        "description": "Learn basic bel and jaal patterns, cones provided to practice.",
    },
    {
        "event_id": "evt_020",
        "name": "Improv Comedy Workshop",
        "activity_type": "comedy",
        "location": "Defence Phase 4",
        "city": "Karachi",
        "lat": 24.8010, "lng": 67.0480,
        "time": "Tonight, 8:00 PM",
        "price": "PKR 1000",
        "host_name": "Yes, And! Karachi",
        "host_phone": "923001234520",
        "description": "Games-based improv session, no acting experience required.",
    },
    {
        "event_id": "evt_021",
        "name": "Board Game Café Evening",
        "activity_type": "board games",
        "location": "F-7 Markaz",
        "city": "Islamabad",
        "lat": 33.7180, "lng": 73.0630,
        "time": "Today, 6:30 PM",
        "price": "PKR 900",
        "host_name": "Daftarkhwan Games Corner",
        "host_phone": "923001234521",
        "description": "Open board game library plus a hosted Catan tournament round.",
    },
    {
        "event_id": "evt_022",
        "name": "D&D One-Shot Night",
        "activity_type": "tabletop roleplay",
        "location": "F-8",
        "city": "Islamabad",
        "lat": 33.7080, "lng": 73.0430,
        "time": "Tonight, 7:00 PM",
        "price": "PKR 700",
        "host_name": "Roll for Islamabad",
        "host_phone": "923001234522",
        "description": "Pre-made characters, single self-contained adventure, new players welcome.",
    },
    {
        "event_id": "evt_023",
        "name": "Watercolor Painting Workshop",
        "activity_type": "painting",
        "location": "Blue Area",
        "city": "Islamabad",
        "lat": 33.7100, "lng": 73.0550,
        "time": "Today, 4:30 PM",
        "price": "PKR 1300",
        "host_name": "Studio Rung",
        "host_phone": "923001234523",
        "description": "Loose watercolor florals, paper and paints included.",
    },
    {
        "event_id": "evt_024",
        "name": "Leather Crafting Session",
        "activity_type": "leather crafting",
        "location": "G-9 Markaz",
        "city": "Islamabad",
        "lat": 33.6940, "lng": 73.0330,
        "time": "Tomorrow, 5:00 PM",
        "price": "PKR 2200",
        "host_name": "Hide & Stitch",
        "host_phone": "923001234524",
        "description": "Stitch a small leather card holder, tools provided.",
    },
    {
        "event_id": "evt_025",
        "name": "Resin Art Coasters Workshop",
        "activity_type": "resin art",
        "location": "E-11",
        "city": "Islamabad",
        "lat": 33.6960, "lng": 72.9670,
        "time": "Today, 5:00 PM",
        "price": "PKR 1900",
        "host_name": "Pour & Cure Studio",
        "host_phone": "923001234525",
        "description": "Pour and marble your own resin coaster set, set of 4 to take home.",
    },
    {
        "event_id": "evt_026",
        "name": "Karaoke Night",
        "activity_type": "karaoke",
        "location": "F-6",
        "city": "Islamabad",
        "lat": 33.7210, "lng": 73.0890,
        "time": "Tonight, 8:00 PM",
        "price": "PKR 600",
        "host_name": "Mic Drop Lounge",
        "host_phone": "923001234526",
        "description": "Sign up for a song slot, group booths available for larger groups.",
    },
    {
        "event_id": "evt_027",
        "name": "Open Mic Acoustic Sessions",
        "activity_type": "open mic",
        "location": "Centaurus Mall Area",
        "city": "Islamabad",
        "lat": 33.7010, "lng": 73.0530,
        "time": "Today, 7:00 PM",
        "price": "PKR 500",
        "host_name": "Unplugged Isb",
        "host_phone": "923001234527",
        "description": "Acoustic sets and spoken word, five-minute slots, sign up at the door.",
    },
    {
        "event_id": "evt_028",
        "name": "Board Game Design Jam",
        "activity_type": "board games",
        "location": "I-8 Markaz",
        "city": "Islamabad",
        "lat": 33.6850, "lng": 73.0770,
        "time": "Tomorrow, 4:00 PM",
        "price": "PKR 1000",
        "host_name": "Meeple Makers",
        "host_phone": "923001234528",
        "description": "Prototype a mini game in small teams, playtest at the end.",
    },
    {
        "event_id": "evt_029",
        "name": "Weekend Pottery for Beginners",
        "activity_type": "pottery",
        "location": "Bahria Town Phase 4",
        "city": "Islamabad",
        "lat": 33.5230, "lng": 73.1000,
        "time": "This weekend, 3:00 PM",
        "price": "PKR 1600",
        "host_name": "Terra Studio",
        "host_phone": "923001234529",
        "description": "Hand-building basics with clay, no wheel experience needed.",
    },
    {
        "event_id": "evt_030",
        "name": "Sketchbook & Chai Meetup",
        "activity_type": "drawing",
        "location": "Johar Town",
        "city": "Lahore",
        "lat": 31.4640, "lng": 74.2650,
        "time": "Today, 5:00 PM",
        "price": "PKR 400",
        "host_name": "Doodle Circle",
        "host_phone": "923001234530",
        "description": "Casual sketching over chai, bring any sketchbook or borrow one.",
    },
]
